### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by NecessaryHat** [jxtt-dev/battlemetrics_hour_summary#1]
Is there any chance that you can port this to be able to run it as a firefox extension.

**Comment by jxtt-dev** [comment]
Firefox port is now available here: [https://addons.mozilla.org/en-GB/firefox/addon/battlemetrics-hour-summary/](https://addons.mozilla.org/en-GB/firefox/addon/battlemetrics-hour-summary/)
